[package]
name = "math-evaluator"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
libc = "0.2.159"
spark-jit = { path = "../spark-jit" }

[[bin]]
name = "math-evaluator"
path = "examples/main.rs"
