[package]
name = "math-evaluator"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib", "staticlib"]

[dependencies]
ctor = "0.2.8"
hex = "0.4.3"
libc = "0.2.159"
sha2 = "0.10.8"
spark-jit = { path = "../spark-jit" }
