[package]
name = "math-evaluator"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib", "staticlib"]

[dependencies]
ctor = "0.2.8"
libc = "0.2.159"
spark-jit = { path = "../spark-jit" }
